## Cafe Sales Cleaning

In [1]:
#importing the library
import pandas as pd

In [2]:
#reading the csv file
df = pd.read_csv("dirty_cafe_sales - Copy.csv")
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [3]:
#rows and columns
df.shape

(10000, 8)

In [4]:
#first 5 rows
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [5]:
#last 5 rows
df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [6]:
#checking the data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [7]:
#checking the null values
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

## Data Cleaning

In [8]:
# standardizing column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.columns.tolist()

['transaction_id',
 'item',
 'quantity',
 'price_per_unit',
 'total_spent',
 'payment_method',
 'location',
 'transaction_date']

In [9]:
# to identify the wrong values
df['item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

In [10]:
#-- Items ---
df['item']= df['item'].str.strip()
df['item'] = df['item'].replace({'ERROR': pd.NA, 'UNKNOWN': pd.NA,'': pd.NA})
df['item'] = df['item'].fillna('Others')
df['item'].head(10)
df['item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'Others',
       'Sandwich', 'Juice', 'Tea'], dtype=object)

In [11]:
#-- Quantity ---
df['quantity'] = df['quantity'].replace({'ERROR':pd.NA, 'UNKNOWN':pd.NA, '':pd.NA})
df['quantity'] =  pd.to_numeric(df['quantity'], errors = 'coerce')
df['quantity'] = df['quantity'].fillna(df['quantity'].median())
df['quantity'].head(10)
df['quantity'].isnull().sum()

0

In [12]:
#-- Price per unit
df['price_per_unit'] = df['price_per_unit'].replace({'ERROR':pd.NA, 'UNKNOWN':pd.NA, '':pd.NA})
df['price_per_unit'] = pd.to_numeric(df['price_per_unit'], errors='coerce')
df['price_per_unit'] = df['quantity'].fillna(df['quantity'].median())
df['price_per_unit'].head()

0    2.0
1    4.0
2    4.0
3    2.0
4    2.0
Name: price_per_unit, dtype: float64

In [13]:
# total spent
df['total_spent'] = df['total_spent'].replace({'ERROR':pd.NA, 'UNKNOWN':pd.NA, '':pd.NA})
df['total_spent'] = pd.to_numeric(df['total_spent'], errors='coerce')
df['total_spent'] = (df['quantity'] * df['price_per_unit']).round(2)
df['total_spent'].head()

0     4.0
1    16.0
2    16.0
3     4.0
4     4.0
Name: total_spent, dtype: float64

In [14]:
df['payment_method'].unique()

array(['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan],
      dtype=object)

In [15]:
#payment method 
df['payment_method'] = df['payment_method'].replace({'ERROR':pd.NA, 'UNKNOWN':pd.NA, 'Error':pd.NA, 'Nan':pd.NA, '':pd.NA})
df['payment_method'] = df['payment_method'].fillna('Unknown')
most_common = df[df['payment_method'] != 'Unknown']['payment_method'].mode()[0]
df['payment_method'] = df['payment_method'].replace('Unknown', most_common)
df['payment_method'] = df['payment_method'].str.strip().str.title()
df['payment_method'].head()
df['payment_method'].isnull().sum()

0

In [16]:
#location
df['location'] = df['location'].replace({'ERROR':pd.NA, 'UNKNOWN':pd.NA, '':pd.NA})
df['location'] = df['location'].fillna('Unknown')
mode_location = df[df['location'] != 'Unknown']['location'].mode()[0]
df['location'] = df['location'].replace('Unknown', mode_location)
df['location'] = df['location'].str.strip().str.title()
df['location'].head()
df['location'].unique()

array(['Takeaway', 'In-Store'], dtype=object)

In [17]:
# transaction_date
df['transaction_date'] = df['transaction_date'].replace({'ERROR':pd.NA, 'UNKNOWN':pd.NA, '':pd.NA})
df['transaction_date'] = pd.to_datetime(df['transaction_date'], errors = 'coerce')
df = df.sort_values('transaction_date')
df['transaction_date'] = df['transaction_date'].ffill()

## Saving the clean csv file

In [18]:
df.to_excel('Cafe_Sales_Clean.xlsx', sheet_name = 'Clean_Data', index = False)